import { GoalItem } from '@/@types/goal';
import { createReStateMethods } from '@raulpesilva/re-state';

const GOALS_KEY = 'goals';
const initialValue: GoalItem[] = [
  {
    id: 1,
    product_id: 1,
    title: 'Meta 1',
    type: 'quantity',
    value: 10,
    target: 0,
    completed: null,
    notified: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 2,
    product_id: 1,
    title: 'Meta 2',
    type: 'quantity',
    value: 10,
    target: 10,
    completed: new Date(),
    notified: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 3,
    product_id: 2,
    title: 'Meta 3',
    type: 'quantity',
    value: 12,
    target: 3,
    completed: null,
    notified: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 4,
    product_id: 2,
    title: 'Meta 4',
    type: 'amount',
    value: 10,
    target: 0,
    completed: new Date(),
    notified: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 5,
    product_id: 3,
    title: 'Meta 5',
    type: 'amount',
    value: 100,
    target: 92,
    completed: null,
    notified: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 6,
    product_id: 3,
    title: 'Meta 6',
    type: 'quantity',
    value: 10,
    target: 7,
    completed: null,
    notified: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 7,
    product_id: 4,
    title: 'Meta 7',
    type: 'quantity',
    value: 10,
    target: 0,
    completed: null,
    notified: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 8,
    product_id: 4,
    title: 'Meta 8',
    type: 'amount',
    value: 10,
    target: 10,
    completed: new Date(),
    notified: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 9,
    product_id: 5,
    title: 'Meta 9',
    type: 'quantity',
    value: 10,
    target: 1,
    completed: null,
    notified: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    id: 10,
    product_id: 5,
    title: 'Meta 10',
    type: 'amount',
    value: 10,
    target: 2,
    completed: null,
    notified: null,
    created_at: new Date(),
    updated_at: new Date(),
  },
];

const methods = createReStateMethods(GOALS_KEY, initialValue);

export const { dispatchGoals, useGoalsSelect, getGoals } = methods;
